apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: albums-store
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
